API_TOKEN = "8620685344:AAEF7BhFM-3OKki3eQGclvnL5Cb8PG9dlVU"

languages = {
    "ru": {
        "help": "Скачать видео или картинки с тиктока легко😉\nОтправь мне ссылку на видео или картинки.\nЕсли вы заметили ошибки отпишите @phones_parts",
        "invalid_link": "Неверная ссылка, пришлите правильную ссылку. Пример:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Пожалуйста, подождите!\nВаше видео загружается...\nПока загружается видео вы можете подписатся на наш канал @XLRSHOP",
        "likes": "Лайков",
        "comments": "Коментариев",
        "share": "Репостов",
        "views": "Просмотров",
        "nickname": "Ник",
        "large_for_tg": "Вес видео слишком большой для телеграмма(20 МБ лимит), но вы можете скачать видео по ссылке",
    },
    "en": {
        "help": "Download video or images from tiktok easy\nSend me a link of video.\nIf you see bugs message me @phones_parts",
        "invalid_link": "Invalid link, please send the correct link. Example:\nhttps://vm.tiktok.com/XLR_TT_BOT/",
        "wait": "Please wait!\nYour video is on the way...",
        "likes": "likes",
        "comments": "comments",
        "share": "share",
        "views": "views",
        "nickname": "nickname",
        "large_for_tg": "video is too large for telegram(20 MB limit), but you can download video by link",
    },
    "cn": {
        "help": "从抖音下载视频或图片很方便\n从抖音给我发消息。\n如果您发现任何错误，请退订 @phones_parts",
        "invalid_link": "链接无效，请发送正确的链接。示例：\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "请稍候！\n您的视频正在播放中...",
        "likes": "喜欢",
        "comments": "注释",
        "share": "分享",
        "views": "意见",
        "nickname": "昵称",
        "large_for_tg": "视频对于电报来说太大（20 MB限制），但您可以通过链接下载视频",
    },
    "hi": {
        "help": "tiktok Easy से वीडियो या चित्र डाउनलोड करें\nमुझे वीडियो का लिंक भेजें।\nयदि आप बग देखते हैं तो मुझे संदेश भेजें @phones_parts",
        "invalid_link": "अमान्य लिंक, कृपया सही लिंक भेजें। उदाहरण:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "कृपया प्रतीक्षा करें!\nआपका वीडियो आ रहा है...",
        "likes": "पसंद",
        "comments": "टिप्पणियाँ",
        "share": "हिस्सा",
        "views": "विचारों",
        "nickname": "खरोंच",
        "large_for_tg": "वीडियो टेलीग्राम (20 एमबी सीमा) के लिए बहुत बड़ा है, लेकिन आप लिंक द्वारा वीडियो डाउनलोड कर सकते हैं",
    },
    "es": {
        "help": "Descargue videos o imágenes de tiktok fácilmente\nEnvíeme un enlace de video.\nSi ve errores, envíeme un mensaje @phones_parts",
        "invalid_link": "Enlace no válido, envíe el enlace correcto. Ejemplo:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "¡Por favor, espera!\nTu video está en camino...",
        "likes": "likes",
        "comments": "टिप्पणियाँ",
        "share": "शेयर करना",
        "views": "विचारों",
        "nickname": "उपनाम",
        "large_for_tg": "el video es demasiado grande para telegram (límite de 20 MB), pero puede descargar el video por enlace",
    },
    "fr": {
        "help": "Téléchargez des vidéos ou des images depuis tiktok easy\nEnvoyez-moi un lien de vidéo.\nSi vous voyez des bugs, envoyez-moi un message @phones_parts",
        "invalid_link": "Lien invalide, veuillez envoyer le lien correct. Exemple :\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Veuillez patienter !\nVotre vidéo est en cours d'acheminement...",
        "likes": "aime",
        "comments": "commentaires",
        "share": "partager",
        "views": "vues",
        "nickname": "surnom",
        "large_for_tg": "la vidéo est trop grande pour Telegram (limite de 20 Mo), mais vous pouvez télécharger la vidéo par lien",
    },
    "ar": {
        "help": "قم بتنزيل الفيديو أو الصور من tiktok easy \ n أرسل لي رابط فيديو. \ n إذا رأيت أخطاء برسالة لي @phones_parts",
        "invalid_link": "رابط غير صحيح ، يرجى إرسال الرابط الصحيح. مثال: \ nhttps: //vm.tiktok.com/abcdefg/",
        "wait": "الرجاء الانتظار! \ n الفيديو الخاص بك في الطريق ...",
        "likes": "الإعجابات",
        "comments": "تعليقات",
        "share": "شارك",
        "views": "الآراء",
        "nickname": "اسم الشهرة",
        "large_for_tg": "الفيديو كبير جدا بالنسبة ل Telegram (بحد أقصى 20 ميجابايت) ، ولكن يمكنك تنزيل الفيديو عن طريق الرابط",
    },
    "pt": {
        "help": "Baixe o vídeo ou imagens do tiktok easy\nEnvie-me um link do vídeo.\nSe você ver erros, envie-me uma mensagem @phones_parts",
        "invalid_link": "Link inválido, favor enviar o link correto. Exemplo:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Aguarde!\nSeu vídeo está a caminho...",
        "likes": "gosta",
        "comments": "comments",
        "share": "compartilhar",
        "views": "Visualizações",
        "nickname": "apelido",
        "large_for_tg": "o vídeo é demasiado grande para telegrama (limite de 20 MB), mas você pode baixar vídeo por link",
    },
    "id": {
        "help": "Unduh video atau gambar dari tiktok dengan mudah\nKirim saya tautan video.\nJika Anda melihat bug, pesan saya @phones_parts",
        "invalid_link": "Tautan tidak valid, harap kirim tautan yang benar. Contoh:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Harap tunggu!\nVideo Anda sedang dalam proses...",
        "likes": "suka",
        "comments": "",
        "share": "komentar",
        "views": "dilihat",
        "nickname": "nama panggilan",
        "large_for_tg": "video terlalu besar untuk telegram (batas 20 MB), tetapi Anda dapat mengunduh video melalui tautan",
    },


    "pl": {
        "help": "Pobierz wideo lub obrazy z tiktok easy\nWyślij mi link do filmu.\nJeśli zobaczysz błąd, wyślij mi wiadomość @phones_parts",
        "invalid_link": "Nieprawidłowy link, wyślij prawidłowy link. Przykład:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Proszę czekać!\nTwój film jest w drodze...",
        "likes": "polubienia",
        "comments": "komentarze",
        "share": "udostępnij",
        "views": "wyświetlenia",
        "nickname": "przezwisko",
        "large_for_tg": "wideo jest za duże dla telegramu (limit 20 MB), ale możesz pobrać wideo przez link",
    },
    "cs": {
        "help": "Stáhněte si video nebo obrázky z tiktok easy\nPošlete mi odkaz na video.\nPokud uvidíte chyby, napište mi @phones_parts",
        "invalid_link": "Neplatný odkaz, pošlete prosím správný odkaz. Příklad:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Čekejte prosím!\nVaše video je na cestě...",
        "likes": "lajky",
        "comments": "komentáře",
        "share": "sdílet",
        "views": "pohledy",
        "nickname": "přezdívka",
        "large_for_tg": "video je příliš velké pro telegram (limit 20 MB), ale můžete si stáhnout video pomocí odkazu",
    },
    "de": {
        "help": "Laden Sie Videos oder Bilder von tiktok einfach herunter\nSenden Sie mir einen Video-Link.\nWenn Sie Fehler sehen, senden Sie mir eine Nachricht @phones_parts",
        "invalid_link": "Ungültiger Link, bitte senden Sie den richtigen Link. Beispiel:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Bitte warten!\nIhr Video ist unterwegs...",
        "likes": "Likes",
        "comments": "Kommentare",
        "share": "Teilen",
        "views": "Ansichten",
        "nickname": "Spitzname",
        "large_for_tg": "Video ist zu groß für Telegramm (20 MB Limit), aber Sie können Video über Link herunterladen",
    },
    "it": {
        "help": "Scarica video o immagini da tiktok easy\nInviami un link al video.\nSe vedi dei bug, inviami un messaggio @phones_parts",
        "invalid_link": "Link non valido, inviare il link corretto. Esempio:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Attendi!\nIl tuo video è in arrivo...",
        "likes": "piace",
        "comments": "Commenti",
        "share": "Condividere",
        "views": "visualizzazioni",
        "nickname": "soprannome",
        "large_for_tg": "il video è troppo grande per telegramma (limite di 20 MB), ma è possibile scaricare video tramite link",
    },
    "tr": {
        "help": "Tiktok easy'den video veya resim indirin\nBana bir video bağlantısı gönderin.\nHata görürseniz bana mesaj atın @phones_parts",
        "invalid_link": "Geçersiz bağlantı, lütfen doğru bağlantıyı gönderin. Örnek:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Lütfen bekleyin!\nVideonuz yolda...",
        "likes": "seviyor",
        "comments": "yorumlar",
        "share": "Paylaş",
        "views": "Görüntüleme",
        "nickname": "Takma ad",
        "large_for_tg": "video telgraf için çok büyük (20 MB sınırı), ancak videoyu bağlantıyla indirebilirsiniz",
    },
    "he": {
        "help": "הורד סרטון או תמונות מ-tiktok easy\nשלח לי קישור לסרטון.\nאם אתה רואה באגים שלח לי הודעה @phones_parts",
        "invalid_link": "קישור לא חוקי, נא לשלוח את הקישור הנכון. דוגמה:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "אנא המתן!\nהסרטון שלך בדרך...",
        "likes": "אוהב",
        "comments": "הערות",
        "share": "לַחֲלוֹק",
        "views": "צפיות",
        "nickname": "כינוי",
        "large_for_tg": "וידאו גדול מדי עבור מברק (מגבלת 20 MB), אבל אתה יכול להוריד וידאו על ידי קישור",
    },
    "uk": {
        "help": "Легко завантажуйте відео або зображення з tiktok\nНадішліть мені посилання на відео.\nЯкщо ви бачите помилки, напишіть мені @phones_parts",
        "invalid_link": "Недійсне посилання, надішліть правильне посилання. Приклад:\nhttps://vm.tiktok.com/abcdefg/",
        "wait": "Будь ласка, зачекайте!\nВаше відео в дорозі...",
        "likes": "Лайків",
        "comments": "Коментарів",
        "share": "Поділитися",
        "views": "Переглядів",
        "nickname": "Нік",
        "large_for_tg": "відео занадто велике для telegram(обмеження в 20 МБ), але ви можете завантажити відео за посиланням",
    },
}
